name: Thermite 🔥

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  assemble:
    name: Assemble
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17','19' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Assemble
        run: make assemble

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: 19
          cache: 'gradle'
      - name: Lint
        run: make lint

  test:
    name: "Test & Report"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: 19
          cache: 'gradle'

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Appium & Drivers
        run: |
          brew install appium
          appium driver install uiautomator2

      - name: Run Appium
        run: make appium-start

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Test
        uses: reactivecircus/android-emulator-runner@v2.34.0
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          script: make report

      - name: Stop Appium
        if: always()
        run: make appium-stop

      - name: Report
        uses: codecov/codecov-action@v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
